// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJbeSW6VFXgVZ_zobE75bsk8Swhos2V3g',
    appId: '1:636737039961:web:8966f675437e70e3f44b48',
    messagingSenderId: '636737039961',
    projectId: 'newprogressapp',
    authDomain: 'newprogressapp.firebaseapp.com',
    databaseURL: 'https://newprogressapp-default-rtdb.firebaseio.com',
    storageBucket: 'newprogressapp.appspot.com',
    measurementId: 'G-JFS1VC1L26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX5y_TAGZD0rfL_ogGxy0reOEqDfwuFaM',
    appId: '1:636737039961:android:ef2d5fe71e6e29cbf44b48',
    messagingSenderId: '636737039961',
    projectId: 'newprogressapp',
    databaseURL: 'https://newprogressapp-default-rtdb.firebaseio.com',
    storageBucket: 'newprogressapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXcMnVluFyUpPxKe31a4QkgTyCh8wn1Ag',
    appId: '1:636737039961:ios:863ec82b7ee4c3a0f44b48',
    messagingSenderId: '636737039961',
    projectId: 'newprogressapp',
    databaseURL: 'https://newprogressapp-default-rtdb.firebaseio.com',
    storageBucket: 'newprogressapp.appspot.com',
    iosClientId: '636737039961-dt28ff0kfu9fg908b7daulmc5ualg1e9.apps.googleusercontent.com',
    iosBundleId: 'com.example.npApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXcMnVluFyUpPxKe31a4QkgTyCh8wn1Ag',
    appId: '1:636737039961:ios:06bc4a8ab03ebb93f44b48',
    messagingSenderId: '636737039961',
    projectId: 'newprogressapp',
    databaseURL: 'https://newprogressapp-default-rtdb.firebaseio.com',
    storageBucket: 'newprogressapp.appspot.com',
    iosClientId: '636737039961-0cu93gti7ec21fufo55ade9859u3jf0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.npApp.RunnerTests',
  );
}
